/**
 * @created        17/06/2023 - 15:26
 * @author         Nariman Palangi
 * @user           ragnarok
 * @organization
 * @project        boilerplate-vue-3
 * @file name      icons.js
 * @file dir       src/plugins/vuetify-options
 * @see https://vuetifyjs.com/en/features/icon-fonts/
 */

// import '@mdi/font/css/materialdesignicons.css'

import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import { cli } from "@/plugins/vuetify-options/icons/classinoIcons";
import {
    mdiAccount,
    mdiLogout,
    mdiLightbulb,
    mdiLightbulbOnOutline,
    mdiArrowLeft,
    mdiArrowRight,
    mdiEye,
    mdiEyeOutline,
    mdiEyeOff,
    mdiEyeOffOutline,
    mdiLockOutline,
    mdiDotsVertical,
    mdiTimerOutline,
    mdiPencilCircleOutline,
    mdiUnfoldMoreHorizontal,
    mdiChevronLeft,
    mdiChevronRight,
    mdiChevronLeftCircle,
    mdiChevronRightCircle,
    mdiAccountOutline,
    mdiCurrencyUsd,
    mdiWeatherSunny,
    mdiWeatherNight,
    mdiThemeLightDark,
    mdiCartOutline,
    mdiChatOutline,
    mdiBellOutline,
    mdiEmoticonSadOutline,
    mdiMagnify,
    mdiInstagram,
    mdiWhatsapp,
    mdiSendCircle,
    mdiSend,
    mdiMicrophone,
    mdiPaperclip,
    mdiTrashCanOutline,
    mdiCheck,
    mdiCheckAll,
    mdiAccountSchoolOutline,
    mdiClockOutline,
    mdiLockOpenVariantOutline,
    mdiFilterOutline,
    mdiCancel,
    mdiAccountCancelOutline,
    mdiFileDownloadOutline,
    mdiListBoxOutline,
    mdiFileUploadOutline,
    mdiTextBoxCheckOutline,
    mdiForumOutline,
    mdiClose,
    mdiImageMultipleOutline,
    mdiImageOutline,
    mdiImageSizeSelectLarge,
    mdiCheckOutline,
    mdiCheckCircleOutline,
    mdiCloseCircleOutline,
    mdiListStatus,
    mdiFinance,
    mdiCartPlus,
    mdiBookmark,
    mdiPlus,
    mdiAlert,
    mdiPlayOutline,
    mdiMenu,
    mdiCash,
    mdiCreditCardCheckOutline,
    mdiAlertOutline,
    mdiChevronDown,
    mdiChevronUp,
    mdiAccountCreditCardOutline,
    mdiSecurity,
    mdiPencil,
    mdiBookOpenVariantOutline,
    mdiStorePlusOutline,
    mdiCreditCardOutline,
    mdiPencilRulerOutline,
    mdiPencilOutline,
    mdiInvoiceListOutline,
    mdiDeskLamp,
    mdiCalendarMonth,
    mdiRadioboxMarked,
    mdiCreditCard,
    mdiBookOpenVariant,
    mdiMoonWaningCrescent,
    mdiCircle,
    mdiDownloadOutline,
    mdiDotsCircle,
    mdiClockAlertOutline,
    mdiAccountCircleOutline,
    mdiMoonWaxingCrescent,
    mdiChatQuestionOutline,
    mdiStop,
    mdiMinus,
    mdiCellphoneArrowDown,
    mdiExportVariant,
    mdiPlusBoxOutline,
    mdiCellphoneArrowDownVariant,
    mdiInformationOutline,
    mdiCircleSmall,
    mdiExclamation

} from '@mdi/js'

/** @description config icon sets  for vuetify */

/**  to set icons
 *   @constant
 *   @type {string}
 *   @default mdi
 *  **/
const defaultIconSet = "mdi";
export default {
  defaultSet: defaultIconSet, // This is already the default value - only for display purposes,
  aliases: {
    ...aliases,
      account: mdiAccount,
      mdiAccountOutline,
      mdiLogout,
      lightBulb:mdiLightbulb,
      lightBulbOnOutline :mdiLightbulbOnOutline,
      arrowLeft : mdiArrowLeft,
      arrowRight : mdiArrowRight,
      mdiEye,
      mdiEyeOutline,
      mdiEyeOff,
      mdiEyeOffOutline,
      mdiLockOutline,
      mdiLockOpenVariantOutline,
      mdiDotsVertical,
      mdiTimerOutline,
      mdiPencilCircleOutline,
      mdiUnfoldMoreHorizontal,
      mdiChevronLeft,
      mdiChevronRight,
      mdiChevronLeftCircle,
      mdiChevronRightCircle,
      mdiCurrencyUsd,
      mdiWeatherSunny,
      mdiWeatherNight,
      mdiThemeLightDark,
      mdiCartOutline,
      mdiChatOutline,
      mdiBellOutline,
      mdiFilterOutline,
      mdiEmoticonSadOutline,
      mdiMagnify,
      mdiInstagram,
      mdiWhatsapp,
      mdiSendCircle,
      mdiSend,
      mdiMicrophone,
      mdiPaperclip,
      mdiTrashCanOutline,
      mdiCheck,
      mdiCheckAll,
      mdiAccountSchoolOutline,
      mdiClockOutline,
      mdiCancel,
      mdiAccountCancelOutline,
      mdiFileDownloadOutline,
      mdiListBoxOutline,
      mdiFileUploadOutline,
      mdiTextBoxCheckOutline,
      mdiForumOutline,
      mdiClose,
      mdiImageMultipleOutline,
      mdiImageOutline,
      mdiImageSizeSelectLarge,
      mdiCheckOutline,
      mdiCheckCircleOutline,
      mdiCloseCircleOutline,
      mdiListStatus,
      mdiFinance,
      mdiCartPlus,
      mdiBookmark,
      mdiPlus,
      mdiAlert,
      mdiPlayOutline,
      mdiMenu,
      mdiCash,
      mdiCreditCardCheckOutline,
      mdiAlertOutline,
      mdiChevronDown,
      mdiChevronUp,
      mdiAccountCreditCardOutline,
      mdiSecurity,
      mdiPencil,
      mdiBookOpenVariantOutline,
      mdiStorePlusOutline,
      mdiCreditCardOutline,
      mdiPencilRulerOutline,
      mdiPencilOutline,
      mdiInvoiceListOutline,
      mdiDeskLamp,
      mdiCalendarMonth,
      mdiCreditCard,
      mdiBookOpenVariant,
      mdiMoonWaningCrescent,
      mdiCircle,
      mdiDownloadOutline,
      mdiRadioboxMarked,
      mdiDotsCircle,
      mdiClockAlertOutline,
      mdiAccountCircleOutline,
      mdiMoonWaxingCrescent,
      mdiChatQuestionOutline,
      mdiStop,
      mdiMinus,
      mdiCellphoneArrowDown,
      mdiExportVariant,
      mdiPlusBoxOutline,
      mdiCellphoneArrowDownVariant,
      mdiInformationOutline,
      mdiCircleSmall,
      mdiExclamation
  },
  sets: {
      mdi,
      cli,
  },
}
