import {required, mobile, numeric} from "@/composable/useValidator";
import {FIELD_OF_STUDY, GRADE_ITEMS} from "@/constants/educational";

export const SCHEMA = {
    /* Form SCHEMA */
    schema: [
        {
            id: "grade",
            label: "پایه تحصیلی",
            placeholder: "",
            color: 'primary',
            items: GRADE_ITEMS,
            itemTitle: 'name',
            itemValue: 'id',
            multiple: true,
            chips: false,
            clearable: true,
            hideDetails: true,
            cols: 12,
            xl: 2,
            lg: 2,
            md: 4,
            sm: 12,
            rounded: 'lg',
            type: "autocomplete",
        },
        {
            id: "fields",
            label: "رشته تحصیلی",
            placeholder: "",
            color: 'primary',
            hideDetails: true,
            itemTitle: 'name',
            itemValue: 'id',
            items: [],
            multiple: true,
            chips: false,
            clearable: true,
            cols: 12,
            xl: 2,
            lg: 2,
            md: 4,
            sm: 12,
            rounded: 'lg',
            type: "autocomplete",
        },
        {
            id: "lesson",
            label: "درس",
            placeholder: "",
            color: 'primary',
            multiple: true,
            items: [],
            itemTitle: 'name',
            itemValue: 'id',
            chips: false,
            clearable: true,
            hideDetails: true,
            cols: 12,
            xl: 2,
            lg: 2,
            md: 4,
            sm: 12,
            rounded: 'lg',
            type: "autocomplete",
        },
        {
            id: "professor",
            label: "استاد",
            placeholder: "",
            color: 'primary',
            multiple: true,
            items: [],
            itemTitle: 'name',
            itemValue: 'id',
            chips: false,
            clearable: true,
            hideDetails: true,
            cols: 12,
            xl: 2,
            lg: 2,
            md: 4,
            sm: 12,
            rounded: 'lg',
            type: "autocomplete",
        },
        {
            id: "course",
            label: "دوره",
            placeholder: "",
            color: 'primary',
            multiple: true,
            items: [],
            itemTitle: 'name',
            itemValue: 'id',
            chips: false,
            clearable: true,
            hideDetails: true,
            cols: 12,
            xl: 2,
            lg: 2,
            md: 4,
            sm: 12,
            rounded: 'lg',
            type: "autocomplete",
        },
        {
            id: "free",
            label: "فقط رایگان‌ها",
            placeholder: "",
            hideDetails: true,
            cols: 12,
            xl: 1,
            lg: 1,
            md: 4,
            sm: 12,
            rounded: 'lg',
            inset: false,
            color: 'primary',
            type: "switch",
        },
    ],

    /* Form MODEL */
    model: {
        grade: null,
        fields: null,
        lesson: null,
        professor: null,
        course: null,
        free: null,

    },

    /* VALIDATION SCHEMA */
    validations: {
        grade: {},
        fields: {},
        lesson: {},
        professor: {},
        course: {},
        free: {},
    },
};
