import {required, city, sameAs} from "@/composable/useValidator";
import {FAMILIARITY_WAYS, FIELD_OF_STUDY, GENDER, GRADE_ITEMS} from "@/constants/educational";
import {PROVINCES} from "@/constants/regions";


export const SCHEMA = {
    /* Form SCHEMA */
    schema: [
        {
            id: "mobile",
            placeholder: "موبایل",
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            variant: 'solo',
            bgColor: 'background',
            rounded: 'xl',
            flat: true,
            type: "text",
            disabled: true,
            readOnly: true,
        },
        {
            id: "name",
            placeholder: "نام و نام خانوادگی",
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            variant: 'solo',
            bgColor: 'background',
            rounded: 'xl',
            flat: true,
            type: "text",
        },
        {
            id: "name_english",
            placeholder: "نام و نام خانوادگی به انگلیسی",
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            variant: 'solo',
            bgColor: 'background',
            rounded: 'xl',
            flat: true,
            type: "text",
        },
        {
            id: "province",
            label: "استان",
            placeholder: "استان",
            variant: 'solo',
            bgColor: 'background',
            items: PROVINCES,
            itemTitle: 'title',
            itemValue: 'value',
            multiple: false,
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
        {
            id: "city",
            label: "شهر",
            placeholder: "شهر لطفا شهر خود را انتخاب کنید.",
            variant: 'solo',
            bgColor: 'background',
            items: [],
            itemTitle: 'name',
            itemValue: 'code',
            multiple: false,
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
        {
            id: "grade",
            label: "پایه تحصیلی",
            placeholder: "پایه تحصیلی",
            variant: 'solo',
            bgColor: 'background',
            items: GRADE_ITEMS,
            itemTitle: 'title',
            itemValue: 'value',
            multiple: false,
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
        {
            id: "field_of_study",
            label: "رشته تحصیلی",
            placeholder: "رشته تحصیلی",
            variant: 'solo',
            bgColor: 'background',
            items: FIELD_OF_STUDY,
            itemTitle: 'title',
            itemValue: 'value',
            multiple: false,
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
        {
            id: "sex",
            placeholder: "جنسیت",
            label: "جنسیت",
            variant: 'solo',
            bgColor: 'background',
            multiple: false,
            items: GENDER,
            itemTitle: 'title',
            itemValue: 'value',
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
        {
            id: "familiarity_way",
            label: "نحوه آشنایی",
            placeholder: "نحوه آشنایی",
            variant: 'solo',
            bgColor: 'background',
            multiple: false,
            items: FAMILIARITY_WAYS,
            chips: false,
            clearable: true,
            hideDetails: false,
            cols: 12,
            lg: 6,
            md: 6,
            sm: 12,
            rounded: 'xl',
            flat: true,
            type: "select",
        },
    ],

    /* Form MODEL */
    model: {
        mobile: null,
        name: null,
        name_english: null,
        province: null,
        city: null,
        field_of_study: null,
        grade: null,
        sex: null,
        familiarity_way: null,
    },

    /* VALIDATION SCHEMA */
    validations: {
        mobile: { },
        name: { required },
        name_english: { required },
        province: { required },
        city: { required, city },
        field_of_study: { required },
        grade: { required },
        sex: { required },
        familiarity_way: { required },
    },
};